template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "veps1250"
__REPO__ = "lang-vep"
__UND2C__ = "vep"
__UNDEFINED__ = "Veps"
__UND__ = "vep"
