template = "https://github.com/giellalt/template-lang-und"
rev_id = 318
template_sha = "71a1af4cb1cb80e9b86b2e9d1c090f473b0d8270"

[replacements]
__GLOTTOLOG_ID__ = "veps1250"
__REPO__ = "lang-vep"
__UND2C__ = "vep"
__UNDEFINED__ = "Veps"
__UND__ = "vep"
