template = "https://github.com/giellalt/template-lang-und"
rev_id = 329
template_sha = "653a8418c7d2f9872ff8fc37600ef1683d3804ae"

[replacements]
__GLOTTOLOG_ID__ = "veps1250"
__REPO__ = "lang-vep"
__UND2C__ = "vep"
__UNDEFINED__ = "Veps"
__UND__ = "vep"
